name: Nox Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches: [ main ]

jobs:
  nox:
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.optional || true }} # Allow jobs to continue even if one fails, unless optional is false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          # Mark specific combinations as not optional
          - os: ubuntu-22.04
            python-version: "3.11"
            optional: false
          - os: ubuntu-22.04
            python-version: "3.12"
            optional: false
          - os: ubuntu-latest
            python-version: "3.11"
            optional: false
          - os: ubuntu-latest
            python-version: "3.12"
            optional: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Nox
      run: pip install nox
    
    - name: Run Nox
      env:
        GITHUB_PYTHON_VERSION: ${{ matrix.python-version }}
      run: nox